src/Smartstore.Web/Areas/Admin/Controllers/ShipmentController.cs
using System.Data;
using System.Linq.Dynamic.Core;
using System.Net.Mime;
using Dasync.Collections;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Routing;
using Smartstore.Admin.Models.Orders;
using Smartstore.ComponentModel;
using Smartstore.Core.Catalog;
using Smartstore.Core.Catalog.Attributes;
using Smartstore.Core.Catalog.Products;
using Smartstore.Core.Checkout.Orders;
using Smartstore.Core.Checkout.Shipping;
using Smartstore.Core.Common.Services;
using Smartstore.Core.Common.Settings;
using Smartstore.Core.Localization;
using Smartstore.Core.Logging;
using Smartstore.Core.Rules.Filters;
using Smartstore.Core.Security;
using Smartstore.Core.Stores;
using Smartstore.Pdf;
using Smartstore.Web.Models.Common;
using Smartstore.Web.Models.DataGrid;

namespace Smartstore.Admin.Controllers
{
    public class ShipmentController : AdminController
    {
        private readonly SmartDbContext _db;
        private readonly IAddressService _addressService;
        private readonly IProductAttributeMaterializer _productAttributeMaterializer;
        private readonly IOrderProcessingService _orderProcessingService;
        private readonly IPdfConverter _pdfConverter;
        private readonly PdfSettings _pdfSettings;
        private readonly MeasureSettings _measureSettings;
        private readonly CatalogSettings _catalogSettings;

        public ShipmentController(
            SmartDbContext db,
            IAddressService addressService,
            IProductAttributeMaterializer productAttributeMaterializer,
            IOrderProcessingService orderProcessingService,
            IPdfConverter pdfConverter,
            PdfSettings pdfSettings,
            MeasureSettings measureSettings,
            CatalogSettings catalogSettings)
        {
            _db = db;
            _addressService = addressService;
            _productAttributeMaterializer = productAttributeMaterializer;
            _orderProcessingService = orderProcessingService;
            _pdfConverter = pdfConverter;
            _pdfSettings = pdfSettings;
            _measureSettings = measureSettings;
            _catalogSettings = catalogSettings;
        }

        public IActionResult Index()
        {
            return RedirectToAction(nameof(List));
        }

        [Permission(Permissions.Order.Read)]
        public IActionResult List()
        {
            PrepareViewBag();

            return View(new ShipmentListModel());
        }

        [Permission(Permissions.Order.Read)]
        public async Task<IActionResult> ShipmentList(GridCommand command, ShipmentListModel model)
        {
            var dtHelper = Services.DateTimeHelper;

            DateTime? startDate = model.StartDate == null
                ? null
                : dtHelper.ConvertToUtcTime(model.StartDate.Value, dtHelper.CurrentTimeZone);

            DateTime? endDate = model.EndDate == null
                ? null
                : dtHelper.ConvertToUtcTime(model.EndDate.Value, dtHelper.CurrentTimeZone).AddDays(1);

            var query = _db.Shipments.AsNoTracking();

            if (model.TrackingNumber.HasValue())
            {
                query = query.ApplySearchFilterFor(x => x.TrackingNumber, model.TrackingNumber);
            }

            if (model.ShippingMethod.HasValue())
            {
                query = query.ApplySearchFilterFor(x => x.Order.ShippingMethod, model.ShippingMethod);
            }

            if (model.OrderId.GetValueOrDefault() > 0)
            {
                query = query.Where(x => x.OrderId == model.OrderId.Value);
            }

            var shipments = await query
                .Include(x => x.Order)
                .Where(x => x.Order != null)
                .ApplyTimeFilter(startDate, endDate)
                .ApplyGridCommand(command, false)
                .ToPagedList(command)
                .LoadAsync();

            var rows = await shipments.SelectAsync(async x =>
            {
                var m = new ShipmentModel();
                await PrepareShipmentModel(m, x, false);
                return m;
            })
            .AsyncToList();

            return Json(new GridModel<ShipmentModel>
            {
                Rows = rows,
                Total = shipments.TotalCount
            });
        }

        [Permission(Permissions.Order.EditShipment)]
        public async Task<IActionResult> Create(int orderId)
        {
            var order = await _db.Orders
                .IncludeCustomer(true)
                .IncludeOrderItems()
                .IncludeShipments()
                .FindByIdAsync(orderId);

            if (order == null)
            {
                return NotFound();
            }

            var model = new ShipmentModel
            {
                OrderId = order.Id,
            };

            var orderItemIds = order.OrderItems.ToDistinctArray(x => x.Id);
            if (orderItemIds.Any())
            {
                var baseWeight = await _db.MeasureWeights.FindByIdAsync(_measureSettings.BaseWeightId, false);
                var baseDimension = await _db.MeasureDimensions.FindByIdAsync(_measureSettings.BaseDimensionId, false);

                foreach (var orderItem in order.OrderItems)
                {
                    // We can ship only shippable products.
                    if (!orderItem.Product.IsShippingEnabled)
                        continue;

                    // Ensure that this product can be added to a shipment.
                    if (await _orderProcessingService.GetShippableItemsCountAsync(orderItem) <= 0)
                        continue;

                    var itemModel = await CreateShipmentItemModel(null, orderItem, baseDimension, baseWeight);
                    if (itemModel != null)
                    {
                        model.Items.Add(itemModel);
                    }
                }
            }

            PrepareViewBag();

            return View(model);
        }

        [HttpPost, ParameterBasedOnFormName("save-continue", "continueEditing")]
        [FormValueRequired("save", "save-continue")]
        [Permission(Permissions.Order.EditShipment)]
        public async Task<IActionResult> Create(ShipmentModel model, IFormCollection form, bool continueEditing)
        {
            var order = await _db.Orders
                .IncludeCustomer(true)
                .IncludeOrderItems()
                .IncludeShipments()
                .FindByIdAsync(model.OrderId);

            if (order == null)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                var quantities = new Dictionary<int, int>();

                foreach (var orderItem in order.OrderItems)
                {
                    foreach (var key in form.Keys)
                    {
                        if (key.EqualsNoCase($"qtyToAdd{orderItem.Id}"))
                        {
                            quantities.Add(orderItem.Id, form[key].FirstOrDefault().ToInt());
                            break;
                        }
                    }
                }

                var shipment = await _orderProcessingService.AddShipmentAsync(order, model.TrackingNumber, model.TrackingUrl, quantities);
                if (shipment != null)
                {
                    Services.ActivityLogger.LogActivity(KnownActivityLogTypes.EditOrder, T("ActivityLog.EditOrder"), order.GetOrderNumber());
                    NotifySuccess(T("Admin.Orders.Shipments.Added"));

                    return continueEditing
                       ? RedirectToAction(nameof(Edit), new { id = shipment.Id })
                       : RedirectToAction(nameof(OrderController.Edit), "Order", new { id = order.Id });
                }
                else
                {
                    NotifyError(T("Admin.Orders.Shipments.NoProductsSelected"));

                    return RedirectToAction(nameof(Create), new { orderId = order.Id });
                }
            }

            return await Create(order.Id);
        }

        [Permission(Permissions.Order.Read)]
        public async Task<IActionResult> Edit(int id)
        {
            var shipment = await _db.Shipments
                .Include(x => x.ShipmentItems)
                .Include(x => x.Order.ShippingAddress.Country)
                .Include(x => x.Order.ShippingAddress.StateProvince)
                .FindByIdAsync(id);

            if (shipment == null)
            {
                return NotFound();
            }

            var model = new ShipmentModel();
            await PrepareShipmentModel(model, shipment, true);
            PrepareViewBag();

            return View(model);
        }

        [HttpPost, ParameterBasedOnFormName("save-continue", "continueEditing")]
        [Permission(Permissions.Order.EditShipment)]
        public async Task<IActionResult> Edit(ShipmentModel model, bool continueEditing)
        {
            var shipment = await _db.Shipments
                .Include(x => x.ShipmentItems)
                .Include(x => x.Order.ShippingAddress.Country)
                .Include(x => x.Order.ShippingAddress.StateProvince)
                .FindByIdAsync(model.Id);

            if (shipment == null)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                shipment.TrackingNumber = model.TrackingNumber;
                shipment.TrackingUrl = model.TrackingUrl;

                await _db.SaveChangesAsync();

                Services.ActivityLogger.LogActivity(KnownActivityLogTypes.EditOrder, T("ActivityLog.EditOrder"), shipment.Order.GetOrderNumber());

                return continueEditing
                    ? RedirectToAction(nameof(Edit), new { id = shipment.Id })
                    : RedirectToAction(nameof(OrderController.Edit), "Order", new { id = shipment.OrderId });
            }

src/Smartstore.Web/Areas/Admin/Views/Shipment/Create.cshtml
@model ShipmentModel

@{
    ViewBag.Title = T("Admin.Orders.Shipments.AddNew.Title", Model.OrderId);
}

<form asp-action="Create" method="post">
    <input type="hidden" asp-for="Id" />
    <input type="hidden" asp-for="OrderId" />

    <div class="section-header">
        <div class="title">
            <i class="fa fa-truck-moving fa-flip-horizontal"></i>
            <span>@ViewBag.Title</span>
            <a asp-action="Edit" asp-controller="Order" asp-route-id="@Model.OrderId">(@T("Admin.Orders.Shipments.BackToOrder"))</a>
        </div>
        <div class="options">
            <zone name="admin_button_toolbar_before" />

            <button type="submit" name="save" value="save" class="btn btn-warning">
                <i class="fa fa-check"></i>
                <span>@T("Admin.Common.Save")</span>
            </button>
            <button type="submit" name="save" value="save-continue" class="btn btn-secondary">
                <span>@T("Admin.Common.SaveContinue")</span>
            </button>

            <zone name="admin_button_toolbar_after" />
        </div>
    </div>

    <div asp-validation-summary="All"></div>

    <div class="adminContent mb-5">
        <div class="adminRow">
            <div class="adminTitle">
                <smart-label asp-for="TrackingNumber" />
            </div>
            <div class="adminData">
                <input asp-for="TrackingNumber" />
                <span asp-validation-for="TrackingNumber"></span>
            </div>
        </div>
        <div class="adminRow">
            <div class="adminTitle">
                <smart-label asp-for="TrackingUrl" />
            </div>
            <div class="adminData">
                <input asp-for="TrackingUrl" />
                <span asp-validation-for="TrackingUrl"></span>
            </div>
        </div>
    </div>

    <h5>@T("Admin.Orders.Shipments.Products")</h5>

    <div class="table-responsive">
        <table class="table admin-table">
            <thead>
                <tr>
                    <th class="w-50">@T("Admin.Orders.Shipments.Products.ProductName")</th>
                    <th>@T("Admin.Orders.Shipments.Products.SKU")</th>
                    <th class="text-center">@T("Admin.Orders.Shipments.Products.QtyOrdered")</th>
                    <th class="text-center">@T("Admin.Orders.Shipments.Products.QtyShipped")</th>
                    <th style="width: 180px;">@T("Admin.Orders.Shipments.Products.QtyToShip")</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Items)
                {
                    var fieldId = $"qtyToAdd{item.OrderItemId}";
                    <tr>
                        <td>
                            <div>
                                @Html.BadgedProductName(item.ProductId, item.ProductName, item.ProductTypeName, item.ProductTypeLabelHint)
                            </div>
                            <div sm-if="item.AttributeInfo.HasValue()">
                                @Html.Raw(item.AttributeInfo)
                            </div>
                        </td>
                        <td>
                            @item.Sku
                        </td>
                        <td class="text-center">
                            @item.QuantityOrdered
                        </td>
                        <td class="text-center">
                            @item.QuantityInAllShipments
                        </td>
                        <td>
                            @Html.Editor(fieldId, "Int32", fieldId, new { htmlAttributes = new { value = item.QuantityToAdd, @class = "form-control-sm" } })
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</form>

src/Smartstore.Web/Areas/Admin/Views/Shipment/Edit.cshtml
@model ShipmentModel

@{
    ViewBag.Title = T("Admin.Orders.Shipments.ViewDetails");

    var displayPdfPackagingSlip = (bool)ViewBag.DisplayPdfPackagingSlip;
}

<form asp-action="Edit" method="post">
    <input type="hidden" asp-for="Id" />
    <input type="hidden" asp-for="OrderId" />

    <div class="section-header">
        <div class="title">
            <i class="fa fa-truck-moving fa-flip-horizontal"></i>
            <span>@ViewBag.Title</span>
            <a asp-action="Edit" asp-controller="Order" asp-route-id="@Model.OrderId">(@T("Admin.Orders.Shipments.BackToOrder"))</a>
        </div>
        <div class="options">
            <zone name="admin_button_toolbar_before" />

            @if (displayPdfPackagingSlip)
            {
                <a asp-action="PdfPackagingSlips" asp-route-all="false" asp-route-selectedIds="@Model.Id" class="btn btn-secondary">
                    <i class="fa fa-print"></i>
                    <span>@T("Admin.Orders.Shipments.PrintPackagingSlip")</span>
                </a>
            }

            <button type="submit" name="save" value="save" class="btn btn-warning">
                <i class="fa fa-check"></i>
                <span>@T("Admin.Common.Save")</span>
            </button>
            <button type="submit" name="save" value="save-continue" class="btn btn-secondary">
                <span>@T("Admin.Common.SaveContinue")</span>
            </button>
            <button type="submit" id="shipment-delete" name="shipment-delete" class="btn btn-danger">
                <i class="far fa-trash-alt"></i>
                <span>@T("Admin.Common.Delete")</span>
            </button>
            <confirm button-id="shipment-delete" />

            <zone name="admin_button_toolbar_after" />
        </div>
    </div>

    <div asp-validation-summary="All"></div>

    <div class="adminContent mb-5">
        <div sm-if="Model.Id != 0" class="adminRow">
            <div class="adminTitle">
                <smart-label asp-for="Id" />
            </div>
            <div class="adminData">
                <input asp-for="Id" sm-plaintext="true" readonly />
            </div>
        </div>
        <div class="adminRow">
            <div class="adminTitle">
                <smart-label asp-for="TrackingNumber" />
            </div>
            <div class="adminData">
                <input asp-for="TrackingNumber" />
                <span asp-validation-for="TrackingNumber"></span>
            </div>
        </div>
        <div class="adminRow">
            <div class="adminTitle">
                <smart-label asp-for="TrackingUrl" />
            </div>
            <div class="adminData">
                <div class="input-group">
                    <input asp-for="TrackingUrl" />
                    <span class="input-group-append">
                        <a id="btn-tracking-url" href="@Model.TrackingUrl" target="_blank" class="btn btn-secondary" title="@T("Common.OpenUrl")">
                            <i class="fa fa-link"></i>
                        </a>
                    </span>
                </div>
                <span asp-validation-for="TrackingUrl"></span>
            </div>
        </div>
        <div class="adminRow">
            <div class="adminTitle">
                <smart-label asp-for="TotalWeight" />
            </div>
            <div class="adminData">
                <input asp-for="TotalWeightString" sm-plaintext="true" readonly />
            </div>
        </div>
        <div class="adminRow">
            <div class="adminTitle">
                <smart-label asp-for="ShippedDate" />
            </div>
            <div class="adminData">
                <div class="form-control-plaintext">
                    @if (Model.ShippedDate.HasValue)
                    {
                        @Model.ShippedDate.ToString()
                    }
                    else
                    {
                        <span class="text-muted">@T("Admin.Orders.Shipments.ShippedDate.NotYet")</span>
                    }
                    @if (Model.CanShip)
                    {
                        <button id="btn-setasshipped" type="button" class="btn btn-sm btn-secondary ml-2 align-text-top" data-url="@Url.Action("SetAsShipped", new { id = Model.Id })">
                            <i class="fa fa-check"></i>
                            <span>@T("Admin.Orders.Shipments.ShippedDate.Button")</span>
                        </button>
                    }
                </div>
            </div>
        </div>
        <div class="adminRow">
            <div class="adminTitle">
                <smart-label asp-for="DeliveryDate" />
            </div>
            <div class="adminData">
                <div class="form-control-plaintext">
                    @if (Model.DeliveryDate.HasValue)
                    {
                        @Model.DeliveryDate.Value.ToString()
                    }
                    else
                    {
                        <span class="text-muted">@T("Admin.Orders.Shipments.DeliveryDate.NotYet")</span>
                    }
                    @if (Model.CanDeliver)
                    {
                        <button id="btn-setasdelivered" type="button" class="btn btn-sm btn-secondary ml-2 align-text-top" data-url="@Url.Action("SetAsDelivered", new { id = Model.Id })">
                            <i class="fa fa-check"></i>
                            <span>@T("Admin.Orders.Shipments.DeliveryDate.Button")</span>
                        </button>
                    }
                </div>
            </div>
        </div>
    </div>

    <h5>@T("Admin.Orders.Shipments.Products")</h5>

    <div class="table-responsive">
        <table class="table admin-table">
            <thead>
                <tr>
                    <th>@T("Admin.Orders.Shipments.Products.ProductName")</th>
                    <th>@T("Admin.Orders.Shipments.Products.SKU")</th>
                    <th class="text-center">@T("Admin.Orders.Shipments.Products.QtyShipped")</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Items)
                {
                    <tr>
                        <td style="width: 70%;">
                            <div>
                                @Html.BadgedProductName(item.ProductId, item.ProductName, item.ProductTypeName, item.ProductTypeLabelHint)
                            </div>
                            <div sm-if="item.AttributeInfo.HasValue()">
                                @Html.Raw(item.AttributeInfo)
                            </div>
                        </td>
                        <td style="width: 15%;">
                            @item.Sku
                        </td>
                        <td class="text-center" style="width: 15%;">
                            @item.QuantityInThisShipment
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</form>

<script sm-target-zone="scripts" data-origin="shipment-edit">
    $(function() {
        // Toggle tracking URL open button.
        $('#@Html.IdFor(model => model.TrackingUrl)').on('change', function () {
            var url = $(this).val() || '';
            $('#btn-tracking-url').attr('href', url).toggleClass('disabled', url.isEmpty());
        }).trigger('change');

        // Set as shipped or delivered.
        $('#btn-setasshipped, #btn-setasdelivered').on('click', function (e) {
            e.preventDefault();
            $(this).postData({ });
            return false;
        });
    });
</script>

src/Smartstore.Web/Areas/Admin/Views/Shipment/List.cshtml
@model ShipmentListModel

@{
    ViewBag.Title = T("Admin.Orders.Shipments.List").Value;

    Assets.BodyAttributes.AppendCssClass("spa-layout");

    var gridViewData = new ViewDataDictionary(ViewData);
    gridViewData["Parent"] = Model;
}

<div class="section-header">
    <div class="title">
        <i class="fa fa-truck-moving fa-flip-horizontal"></i>
        <span>@ViewBag.Title</span>
    </div>
</div>
<div class="options">
    <zone name="admin_button_toolbar_before" />
    <zone name="admin_button_toolbar_after" />
</div>

<partial name="_Grid.Shipments" model="null" view-data="gridViewData" />

src/Smartstore.Web/Areas/Admin/Views/Shipment/_Grid.Shipments.Search.cshtml
@model ShipmentListModel

<div class="form-group">
    <smart-label asp-for="StartDate" />
    <editor asp-for="StartDate" />
</div>
<div class="form-group">
    <smart-label asp-for="EndDate" />
    <editor asp-for="EndDate" />
</div>
<div class="form-group">
    <smart-label asp-for="TrackingNumber" />
    <editor asp-for="TrackingNumber" asp-template="SearchExpression" />
</div>
<div class="form-group">
    <smart-label asp-for="ShippingMethod" />
    <input asp-for="ShippingMethod" />
</div>

src/Smartstore.Web/Areas/Admin/Views/Shipment/_Grid.Shipments.cshtml
@model ShipmentModel

@{
    var orderId = 0;
    var canAddNewShipments = false;
    var parentModel = ViewData["Parent"] as ShipmentListModel;

    if (parentModel == null && ViewData["Parent"] is OrderModel orderModel)
    {
        orderId = orderModel.Id;
        canAddNewShipments = orderModel.CanAddNewShipments;
    }

    var isOrderEditPage = orderId > 0;
    var sortDesc = !isOrderEditPage;

    var displayPdfPackagingSlip = ViewBag.DisplayPdfPackagingSlip != null
        ? (bool)ViewBag.DisplayPdfPackagingSlip
        : false;
}

<datagrid id="shipments-grid"
          allow-resize="true"
          allow-row-selection="displayPdfPackagingSlip"
          preserve-grid-state="true" preserve-command-state="true"
          allow-column-reordering="true">
    <datasource read="@Url.Action("ShipmentList", "Shipment", new { orderId })" />
    <paging position="Bottom" show-size-chooser="true" />
    <sorting allow-unsort="true" allow-multisort="false" enabled="!isOrderEditPage">
        <sort by="CreatedOn" by-entity-member="CreatedOnUtc" descending="@sortDesc" />
    </sorting>
    <toolbar>
        @if (isOrderEditPage)
        {
            if (canAddNewShipments)
            {
                <toolbar-group>
                    <a asp-action="Create" asp-controller="Shipment" asp-route-orderId="@orderId" class="btn btn-primary btn-flat">
                        <i class="fa fa-plus"></i>
                        <span>@T("Admin.Orders.Shipments.AddNew")</span>
                    </a>
                </toolbar-group>
            }
        }
        else
        {
            <toolbar-group>
                <button datagrid-action="DataGridToolAction.ToggleSearchPanel" type="button" class="btn btn-light btn-icon">
                    <i class="fa fa-fw fa-filter"></i>
                </button>
            </toolbar-group>
            <toolbar-group class="dropdown">
                <button type="button" class="btn btn-flat btn-light dropdown-toggle" data-toggle="dropdown">
                    <i class="fa fa-print"></i>
                    <span>@T("Admin.Common.Print")</span>
                </button>
                <div class="dropdown-menu">
                    <a id="packaging-slip-selected" class="dropdown-item" href="javascript:;" v-bind:class="{ 'disabled': !grid.hasSelection }">
                        @T("Admin.Orders.Shipments.PrintPackagingSlip.Selected")
                    </a>
                    <a id="packaging-slip-all" class="dropdown-item" href="javascript:;">
                        @T("Admin.Orders.Shipments.PrintPackagingSlip.All")
                    </a>
                </div>
            </toolbar-group>
        }
        <zone name="datagrid_toolbar_omega"></zone>
    </toolbar>
    @if (!isOrderEditPage)
    {
        <search-panel>
            <partial name="_Grid.Shipments.Search" model="parentModel" />
        </search-panel>
    }
    <columns>
        <column for="Id" hideable="false" halign="center">
            <display-template>
                <div class="text-truncate"><a :href="item.row.EditUrl" class="text-truncate">{{ item.value }}</a></div>
            </display-template>
        </column>
        @if (!isOrderEditPage)
        {
            <column for="OrderNumber" entity-member="Order.OrderNumber">
                <display-template>
                    <div class="text-truncate"><a :href="item.row.OrderEditUrl" class="text-truncate">{{ item.value }}</a></div>
                </display-template>
            </column>
        }
        <column for="TrackingNumber" />
        <column for="TrackingUrl" visible="false">
            <display-template>
                <div class="text-truncate">
                    <a :href="item.row.TrackingUrl" class="text-truncate" target="_blank" v-bind:class="{ hide: item.row.TrackingUrl }">{{ item.value }}</a>
                </div>
            </display-template>
        </column>
        <column for="TotalWeightString" entity-member="TotalWeight" />
        <column for="ShippedDate" entity-member="ShippedDateUtc" />
        <column for="DeliveryDate" entity-member="DeliveryDateUtc" />
        <column for="ShippingMethod" visible="false" entity-member="Order.ShippingMethod" />
        <column for="CreatedOn" entity-member="CreatedOnUtc" />
    </columns>
    <row-commands>
        <a datarow-action="DataRowAction.Custom" :href="item.row.EditUrl">@T("Common.Edit")</a>
    </row-commands>
</datagrid>

<script sm-if="displayPdfPackagingSlip" sm-target-zone="scripts" data-origin="shipments-grid">
    $(function () {
        // Print packaging slip.
        $('#packaging-slip-all, #packaging-slip-selected').on('click', function () {
            var btn = $(this);

            const grid = $('#shipments-grid').parent().data('datagrid');
            var selectedIds = grid.selectedRowKeys;
            var url = '@Url.Action("PdfPackagingSlips", "Shipment", new { area = "Admin" })';

            if (btn.attr('id') === 'packaging-slip-all') {
                url += '?all=true';
            }

            $({}).postData({
                url: url,
                data: { selectedIds }
    		});
        });
    });
</script>